### ISSUE TITLE
Lots of visual glitches in latest version

### ISSUE THREAD

**Issue by jffluis** [santalu/emptyview#30]
In recyclerviews with EmptyView I get a lot of visual glitches like List DivisorItem don't appear well and text from a list item disappears and only appears when I make a scroll gesture.
If I rollback to previous version all works normally.

Version that works well- 1.0.5

I love the new animations btw! Congrats!

**Comment by santalu** [comment]
Hi, thank you for the feedback!

EmptyView now extends from ConstraintLayout. These issues may related to ConstraintLayout. Can you please share the layout that you are using emptyview with it. 

I'll try my best to help you.

**Comment by jffluis** [comment]
Thank you for your response!

Here are the examples:

Fragment layout with empty view and RecyclerView:

`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.SwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/swipeToRefresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.santalu.emptyview.EmptyView xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/empty_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:ev_empty_buttonBackgroundColor="@color/background_gray"
        app:ev_empty_buttonTextColor="@android:color/black"
        app:ev_empty_drawable="@mipmap/app_icon"
        app:ev_error_backgroundColor="@color/background_gray"
        app:ev_error_text="Erro ao obter conteúdo"
        app:ev_error_textColor="@android:color/black"
        app:ev_font="@font/stag_semibold"
        app:ev_loading="circular"
        app:ev_loading_drawableTint="@color/colorPrimary"
        app:ev_loading_title="A carregar..."
        app:ev_transition="slide">


        <android.support.v7.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            android:id="@+id/rv_category"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scrollbars="vertical"
            tools:listitem="@layout/item_category" />

    </com.santalu.emptyview.EmptyView>

</android.support.v4.widget.SwipeRefreshLayout>`



Item : 

`<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"

    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="80dp"
    android:layout_marginTop="2dp"
    app:layout_goneMarginBottom="2dp">

        <android.support.constraint.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="?android:attr/selectableItemBackground"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/txtCategoryName"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_margin="@dimen/text_margin"
                android:layout_marginBottom="8dp"
                android:layout_marginEnd="8dp"
                android:layout_marginLeft="8dp"
                android:layout_marginTop="8dp"
                android:text="Category"
                android:textAppearance="@style/TextMediumListHeader"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@+id/userPhoto"
                app:layout_constraintLeft_toRightOf="@+id/font_awesome"
                app:layout_constraintTop_toTopOf="parent" />

            <com.joanzapata.iconify.widget.IconTextView
                android:id="@+id/font_awesome"
                android:layout_width="50dp"
                android:layout_height="wrap_content"
                android:layout_marginBottom="8dp"
                android:layout_marginLeft="16dp"
                android:layout_marginTop="8dp"
                android:text="O"
                android:textAppearance="@style/TextLarge"
                android:textColor="@android:color/black"
                android:textSize="36sp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.523" />

            <ImageView
                android:id="@+id/userPhoto"
                android:layout_width="20dp"
                android:layout_height="20dp"
                android:layout_marginBottom="8dp"
                android:layout_marginRight="16dp"
                android:layout_marginTop="8dp"
                android:src="@drawable/arrow"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

        </android.support.constraint.ConstraintLayout>
</LinearLayout>`
