### ISSUE TITLE
为什么emptyview里面再使用emptyview时showLoading不现实

### ISSUE THREAD

**Issue by ZjianP** [santalu/emptyview#8]

**Comment by santalu** [comment]
Hi. I'm sorry i didn't quite understand the problem. Could you please give me a little bit of explanation. Thank you.

**Comment by ZjianP** [comment]
就是这样里面有

**Comment by ZjianP** [comment]
像这样使用，第一个EmptyView，使用showLoading()方法，不显示
<?xml version="1.0" encoding="utf-8"?>
<com.santalu.emptyview.EmptyView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/empty_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:emptyButtonText="@string/try_again"
    app:emptyButtonTextColor="@color/colorPrimaryDark"
    app:emptyDrawable="@drawable/ic_sentiment_dissatisfied"
    app:emptyDrawableTint="@color/colorPrimary"

    app:emptyGravity="center"
    app:emptyText="@string/empty"
    app:errorBackgroundColor="@color/red"
    app:errorButtonBackgroundColor="@color/white"
    app:errorButtonText="@string/try_again"
    app:errorButtonTextColor="@color/black"
    app:errorDrawable="@drawable/ic_sentiment_very_dissatisfied"
    app:errorDrawableTint="@color/white"
    app:errorText="@string/emptyview_error_unknown"
    app:errorTextColor="@color/white"
    app:loadingDrawable="@drawable/ic_sentiment_satisfied"
    app:loadingStyle="circular"
    app:loadingText="@string/emptyview_loading"
    app:loadingTint="@color/colorPrimary">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="15dp"
        android:visibility="visible"
        android:background="#98FB98">

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="15dp"
            android:background="#9ACD32"
            android:orientation="vertical">

            <TextView
                android:id="@+id/text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:lineSpacingExtra="1dp"
                android:layout_margin="15dp"
                android:background="#9A32CD"
                android:lineSpacingMultiplier="1.2"
                android:padding="16dp"
                android:text="@string/lorem" />

            <com.santalu.emptyview.EmptyView

                android:id="@+id/empty_view1"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:emptyDrawable="@drawable/ic_sentiment_dissatisfied"
                app:emptyDrawableTint="@color/colorPrimary"
                app:emptyGravity="center"
                app:emptyText="@string/empty"
                app:errorBackgroundColor="@color/red"
                app:errorButtonBackgroundColor="@color/white"
                app:errorButtonText="@string/try_again"
                app:errorButtonTextColor="@color/black"
                app:errorDrawable="@drawable/ic_sentiment_very_dissatisfied"
                app:errorDrawableTint="@color/white"
                app:errorText="@string/emptyview_error_unknown"
                app:errorTextColor="@color/white"
                app:loadingDrawable="@drawable/ic_sentiment_satisfied"
                app:loadingStyle="circular"
                app:loadingText="@string/emptyview_loading"
                app:loadingTint="@color/colorPrimary">


                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_margin="15dp"
                    android:background="#A4D3EE">

                    <TextView
                        android:id="@+id/text1"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:lineSpacingExtra="1dp"
                        android:lineSpacingMultiplier="1.2"
                        android:padding="16dp"
                        android:layout_margin="15dp"
                        android:background="#A0522D"
                        android:text="@string/lorem" />


                </LinearLayout>

            </com.santalu.emptyview.EmptyView>


        </LinearLayout>
    </ScrollView>


</com.santalu.emptyview.EmptyView>
